# Kaggle – DataTops®
Tu profe ha decidido cambiar de aires y, por eso, ha comprado una tienda de portátiles. Sin embargo, su única especialidad es Data Science, por lo que ha decidido crear un modelo de ML para establecer los mejores precios.

¿Podrías ayudar a tu profe a mejorar ese modelo?

## Métrica: RMSE

$$RMSE = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{y}_i)^2}$$

Donde $y_i$ es el valor real y $\hat{y}_i$ es el valor predicho. **Cuanto menor, mejor.**

---
# PARTE 1: Entrenamiento del modelo

## 1. Librerías

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

## 2. Datos

In [2]:
df = pd.read_csv('./data/train.csv', encoding='latin-1')

### 2.1 Exploración de los datos

In [4]:
# Tu código aquí
df.info()
print('\nNulos en total:', df.isnull().sum().sum())

print('\nValores unicos por columna de texto:')
print(df.select_dtypes(include='object').nunique().sort_values())

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         912 non-null    int64
 1   Company           912 non-null    object
 2   Product           912 non-null    object
 3   TypeName          912 non-null    object
 4   Inches            912 non-null    float64
 5   ScreenResolution  912 non-null    object
 6   Cpu               912 non-null    object
 7   Ram               912 non-null    object
 8   Memory            912 non-null    object
 9   Gpu               912 non-null    object
 10  OpSys             912 non-null    object
 11  Weight            912 non-null    object
 12  Price_in_euros    912 non-null    float64
dtypes: float64(2), int64(1), object(10)
memory usage: 92.8+ KB

Nulos en total: 0

Valores unicos por columna de texto:
TypeName              6
Ram                   9
OpSys                 9
Company              19
ScreenResolution     36
Memory               37
Gpu                  93
Cpu                 107
Weight              165
Product             480
dtype: int64

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
0,755,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.86kg,539.00
1,618,Dell,Inspiron 7559,Gaming,15.6,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,1TB HDD,Nvidia GeForce GTX 960<U+039C>,Windows 10,2.59kg,879.01
2,909,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.04kg,900.00
3,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
4,286,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,AMD Radeon R5 M430,Linux,2.25kg,428.00

### 2.2 Definir X e y

In [5]:
# Tu código aquí
y = df['Price_in_euros']
X = df.drop(columns=['Price_in_euros', 'laptop_ID'])

print('X:', X.shape, '| y:', y.shape)
X.head ()

X: (912, 11) | y: (912,)

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.86kg
1,Dell,Inspiron 7559,Gaming,15.6,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,1TB HDD,Nvidia GeForce GTX 960<U+039C>,Windows 10,2.59kg
2,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.04kg
3,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg
4,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,AMD Radeon R5 M430,Linux,2.25kg

### 2.3 Dividir en train y test

In [6]:
# Tu código aquí
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print('Train:', X_train.shape, '| Test:', X_test.shape)

Train: (729, 11) | Test: (183, 11)

## 3. Procesado de datos

> 🚨 **Data leakage:** si usas un scaler, haz **`.fit()` SOLO sobre `X_train`** y luego aplica `.transform()` sobre `X_train` y `X_test` por separado.
>
> Recuerda también que **todo lo que hagas aquí deberás replicarlo después en `test.csv`** (sección 6).

In [7]:
# Tu código aquí
def limpiar(data):
    d = data.copy()
    d['Ram'] = d['Ram'].str.replace('GB', '', regex=False).astype(int)      # '8GB' -> 8
    d['Weight'] = d['Weight'].str.replace('kg', '', regex=False).astype(float)  # '1.86kg' -> 1.86
    d = d.drop(columns=['Product', 'ScreenResolution', 'Cpu', 'Gpu', 'Memory'])
    return d

In [8]:
X_train = pd.get_dummies(limpiar(X_train))
X_test  = pd.get_dummies(limpiar(X_test))

In [9]:
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [10]:
print('Train procesado:', X_train.shape, '| Test procesado:', X_test.shape)
X_train.head()

Train procesado: (729, 35) | Test procesado: (183, 35)

,Inches,Ram,Weight,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,...,TypeName_Workstation,OpSys_Android,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
25,17.3,8,3.00,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
84,15.6,16,2.56,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
10,13.3,8,1.37,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
342,14.0,4,1.54,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
890,17.3,16,2.80,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False

## 4. Modelado

### 4.1 Entrenamiento

In [11]:
# Tu código aquí
modelo = RandomForestRegressor(n_estimators=300, max_depth=20, random_state=42)
modelo.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, n_estimators=300, random_state=42)

### 4.2 Métricas

Recuerda que en la competición se evalúa con **RMSE**.

In [12]:
# Tu código aquí
y_pred = modelo.predict(X_test)
rmse = root_mean_squared_error(y_test, y_pred)
print('RMSE en validacion:', round(rmse, 2), 'euros')

RMSE en validacion: 392.18 euros

### 4.3 Optimización (up to you 🫰🏻)

In [14]:
# Tu código aquí
for n in [100, 300]:
    for prof in [None, 20]:
        m = RandomForestRegressor(n_estimators=n, max_depth=prof, random_state=42)
        m.fit(X_train, y_train)
        r = root_mean_squared_error(y_test, m.predict(X_test))
        print(f'n_estimators={n}, max_depth={prof}  ->  RMSE = {r:.2f}')

importancias = pd.Series(modelo.feature_importances_, index=X_train.columns)
print('\nVariables mas importantes:')
print(importancias.sort_values(ascending=False).head(8))

n_estimators=100, max_depth=None  ->  RMSE = 393.36
n_estimators=100, max_depth=20  ->  RMSE = 395.59
n_estimators=300, max_depth=None  ->  RMSE = 389.33
n_estimators=300, max_depth=20  ->  RMSE = 392.18

Variables mas importantes:
Ram                     0.530055
Weight                  0.167880
TypeName_Notebook       0.119893
Inches                  0.033494
OpSys_Windows 7         0.026689
TypeName_Workstation    0.014662
Company_Razer           0.014034
Company_HP              0.013965
dtype: float64

## 5. Reentrenamiento sobre todos los datos de `train.csv`

Una vez afinado el modelo, reentrenamos con **todos** los datos disponibles antes de predecir sobre `test.csv`.

> ¿Por qué? El split anterior era solo para validar localmente. Para la submission final queremos aprovechar el 100% de los datos de entrenamiento.

In [15]:
# Tu código aquí
X_full = pd.get_dummies(limpiar(X))
columnas_modelo = X_full.columns

modelo_final = RandomForestRegressor(n_estimators=300, max_depth=20, random_state=42)
modelo_final.fit(X_full, y)
print('Modelo final entrenado con', X_full.shape[0], 'portatiles y', X_full.shape[1], 'columnas.')

Modelo final entrenado con 912 portatiles y 37 columnas.

---
# PARTE 2: Predicción y submission

Una vez tengas el modelo listo, toca predecir sobre `test.csv` y generar el archivo de submission.

## 6. Carga los datos de `test.csv`

In [16]:
X_pred = pd.read_csv('./data/test.csv', encoding='latin-1')
X_pred.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,209,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD,Nvidia GeForce GTX 1060,No OS,2.4kg
1,1281,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg
2,1168,Lenovo,V110-15ISK (i3-6006U/4GB/1TB/No,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,Intel HD Graphics 520,No OS,1.9kg
3,1231,Dell,Inspiron 7579,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.191kg
4,1020,HP,ProBook 640,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg

## 7. Replica el procesado en `test.csv`

> ⚠️ Usa `.transform()`, **nunca `.fit_transform()`** sobre los datos de test.
>
> Lo único que **no puedes hacer** es eliminar filas.

In [17]:
# Tu código aquí
ids = X_pred['laptop_ID'].copy()
X_pred_proc = pd.get_dummies(limpiar(X_pred.drop(columns=['laptop_ID'])))

X_pred_proc = X_pred_proc.reindex(columns=columnas_modelo, fill_value=0)

print('Test listo:', X_pred_proc.shape, '| nulos:', int(X_pred_proc.isnull().sum().sum()))

Test listo: (391, 37) | nulos: 0

## 8. Genera la submission

### 8.1 ¿Qué formato espera Kaggle?

In [18]:
sample = pd.read_csv('./data/sample_submission.csv', encoding='latin-1')
sample.head()

   laptop_ID  Price_in_euros
0        209          1949.1
1       1281           805.0
2       1168          1101.0
3       1231          1293.8
4       1020          1832.6

### 8.2 Crea tu submission

In [19]:
# Tu código aquí
predicciones = modelo_final.predict(X_pred_proc)
submission = pd.DataFrame({
    'laptop_ID': ids,
    'Price_in_euros': predicciones
})
submission.head()

   laptop_ID  Price_in_euros
0        209     1391.715344
1       1281      353.995795
2       1168      368.052231
3       1231      863.684781
4       1020     1135.234792

### 8.3 Chequeador

Pásale el chequeador antes de subir a Kaggle. Si todo está bien, guardará el CSV automáticamente con un nombre único.

In [20]:
def checker(df_to_submit, sample, filename=None):
    """
    Valida que tu submission tenga la forma requerida por Kaggle.
    Si es correcta, guarda el CSV listo para subir.
    Si no, lee el mensaje de error y corrígelo.
    """
    if df_to_submit.shape != sample.shape:
        print(' Shape incorrecto.')
        print(f'   Tu submission: {df_to_submit.shape} | Esperado: {sample.shape}')
        print('   Revisa que no hayas borrado filas del test ni añadido/quitado columnas.')
        return

    if not (df_to_submit.columns == sample.columns).all():
        print(' Nombres de columnas incorrectos.')
        print(f'   Tus columnas:       {list(df_to_submit.columns)}')
        print(f'   Columnas esperadas: {list(sample.columns)}')
        return

    if not (df_to_submit['laptop_ID'] == sample['laptop_ID']).all():
        print(' Los IDs no coinciden con sample_submission. Revisa que no hayas reordenado el test.csv.')
        return

    if filename is None:
        from datetime import datetime
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'submission_{timestamp}.csv'

    df_to_submit.to_csv(filename, index=False)
    print(f" ¡Todo correcto! Submission guardada como '{filename}'. ¡A Kaggle!")

In [21]:
checker(submission, sample)

 ¡Todo correcto! Submission guardada como 'submission_20260628_180429.csv'. ¡A Kaggle!